# -*- coding: utf-8 -*-
from __future__ import annotations

import argparse
import json
import logging
import os
from pathlib import Path

# Python 3.13 / Windows loky uyarılarını engelleme
os.environ["LOKY_MAX_CPU_COUNT"] = "4"

import pandas as pd
from src.pipeline import BTCForecastPipeline
from src.visualization import plot_backtest_performance, plot_feature_importance

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s | %(levelname)s | %(message)s",
    datefmt="%Y-%m-%d %H:%M:%S",
)
log = logging.getLogger(__name__)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Bitcoin Quant Forecasting Engine: Custom Financial Loss & Walk-Forward Validation"
    )
    parser.add_argument(
        "--model-type",
        choices=["lightgbm", "xgboost", "elasticnet"],
        default="lightgbm",
        help="Model türü.",
    )
    parser.add_argument(
        "--ensemble",
        action="store_true",
        help="Stacking Meta-Ensemble (LightGBM + XGBoost + ElasticNet) kullanır.",
    )
    parser.add_argument(
        "--no-financial-loss",
        action="store_true",
        help="Standart Binary LogLoss kullanır (Custom Financial Loss kapatılır).",
    )
    parser.add_argument(
        "--n-splits",
        type=int,
        default=5,
        help="Walk-forward fold sayısı.",
    )
    parser.add_argument(
        "--threshold-long",
        type=float,
        default=0.53,
        help="Long sinyali için olasılık eşiği P(Up) >= threshold.",
    )
    parser.add_argument(
        "--threshold-short",
        type=float,
        default=0.00,
        help="Short sinyali için olasılık eşiği P(Up) <= threshold.",
    )
    parser.add_argument(
        "--output-dir",
        type=str,
        default="results",
        help="Tüm rapor ve metrik çıktılarının kaydedileceği klasör.",
    )
    return parser.parse_args()


def generate_markdown_report(payload: dict, output_dir: Path) -> Path:
    """Sonuçları makale ve repo için biçimlendirilmiş Markdown raporuna dönüştürür."""
    bt = payload["backtest_metrics"]
    folds_df = pd.DataFrame(payload["fold_metrics"])
    
    md_content = f"""# Quantitative Research Report: BTC Directional Forecasting
**Model Architecture:** `{payload['model_architecture']}`  
**Custom Financial Loss:** `{payload['use_financial_loss']}`  
**Walk-Forward Folds:** `{payload['n_splits']}`  

---

## 1. Out-of-Sample Walk-Forward Classification Metrics

| Fold | Accuracy | Balanced Accuracy | F1-Score | ROC-AUC | Log-Loss | Brier Score |
| :---: | :---: | :---: | :---: | :---: | :---: | :---: |
"""
    for _, row in folds_df.iterrows():
        md_content += f"| Fold {int(row['fold'])} | %{row['accuracy']*100:.2f} | %{row['balanced_accuracy']*100:.2f} | {row['f1_score']:.4f} | {row['roc_auc']:.4f} | {row['log_loss']:.4f} | {row['brier_score']:.4f} |\n"

    md_content += f"""| **Mean** | **%{folds_df['accuracy'].mean()*100:.2f}** | **%{folds_df['balanced_accuracy'].mean()*100:.2f}** | **{folds_df['f1_score'].mean():.4f}** | **{payload['walk_forward_mean_roc_auc']:.4f}** | **{folds_df['log_loss'].mean():.4f}** | **{folds_df['brier_score'].mean():.4f}** |

---

## 2. Quantitative Backtest & Risk-Adjusted Returns

| Metric | Strategy Result | Benchmark (Buy & Hold) |
| :--- | :--- | :--- |
| **Total Return** | **%{bt['total_return'] * 100:.2f}** | %{bt['benchmark_return'] * 100:.2f} |
| **Annualized Return (CAGR)** | **%{bt['cagr'] * 100:.2f}** | - |
| **Sharpe Ratio (365d)** | **{bt['sharpe_ratio']:.2f}** | - |
| **Annualized Volatility** | %{bt['annualized_volatility'] * 100:.2f} | - |
| **Max Drawdown** | **%{bt['max_drawdown'] * 100:.2f}** | - |
| **Win Rate** | %{bt['win_rate'] * 100:.2f} | - |
| **Total Executed Trades** | {bt['num_trades']} Trades | - |
| **Initial Capital** | ${bt['initial_capital']:,.2f} | ${bt['initial_capital']:,.2f} |
| **Final Portfolio Value** | **${bt['final_value']:,.2f}** | - |

---
*Report automatically generated by BTC_Financial_Econometrics Pipeline.*
"""
    report_path = output_dir / "summary_report.md"
    report_path.write_text(md_content, encoding="utf-8")
    return report_path


def main() -> None:
    args = parse_args()

    use_financial_loss = not args.no_financial_loss
    model_desc = "Stacking_Ensemble" if args.ensemble else args.model_type.upper()

    log.info("Initializing BTC Forecast Pipeline [%s]...", model_desc)
    pipeline = BTCForecastPipeline(
        model_type=args.model_type,
        use_ensemble=args.ensemble,
        use_financial_loss=use_financial_loss,
        threshold_long=args.threshold_long,
        threshold_short=args.threshold_short,
    )

    # 1. Pipeline Çalıştırma
    summary = pipeline.run(n_splits=args.n_splits)

    # 2. Dizin Yönetimi
    output_dir = Path(args.output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)
    figures_dir = Path("reports/figures")
    figures_dir.mkdir(parents=True, exist_ok=True)

    payload = {
        "model_architecture": model_desc,
        "use_financial_loss": use_financial_loss,
        "n_splits": args.n_splits,
        "threshold_long": args.threshold_long,
        "threshold_short": args.threshold_short,
        "walk_forward_mean_roc_auc": summary["mean_score"],
        "walk_forward_std_roc_auc": summary["std_score"],
        "fold_metrics": summary["walk_forward_metrics"],
        "backtest_metrics": summary["backtest_metrics"],
    }

    # 3. Dosyaları Kaydetme (JSON, CSV, Markdown)
    json_path = output_dir / "summary.json"
    json_path.write_text(json.dumps(payload, indent=2, default=str), encoding="utf-8")

    folds_df = pd.DataFrame(summary["walk_forward_metrics"])
    folds_df.to_csv(output_dir / "fold_metrics.csv", index=False)

    md_report_path = generate_markdown_report(payload, output_dir)

    # 4. Otomatik Görselleştirme (Figures Generation)
    if "backtest_df" in summary:
        plot_backtest_performance(
            summary["backtest_df"],
            output_path=figures_dir / "06_equity_curve_and_drawdown.png",
        )

    # Feature Importance Çizimi (En son eğitilen model üzerinden)
    if hasattr(pipeline.model, "feature_importance"):
        importances = pipeline.model.feature_importance()
        if importances is not None:
            # Model girdi feature sütun isimleri
            _, X, _, _, _ = pipeline.build_dataset()
            plot_feature_importance(
                feature_names=X.columns.tolist(),
                importances=importances,
                top_n=15,
                output_path=figures_dir / "07_feature_importance.png",
            )

    # 5. Terminale Formatlanmış Tabloları Yazdırma
    bt = summary["backtest_metrics"]
    print("\n" + "=" * 80)
    print(f"             BTC QUANTITATIVE MODEL PERFORMANCE: {model_desc}")
    print("=" * 80)
    print(f"• Custom Loss Active   : {use_financial_loss}")
    print(f"• Walk-Forward Folds   : {args.n_splits}")
    print(f"• Mean Out-of-Sample ROC-AUC : {summary['mean_score']:.4f} (+/- {summary['std_score']:.4f})\n")

    print("--- [1] WALK-FORWARD FOLD METRICS ---")
    print(folds_df.to_string(index=False, justify="center"))

    print("\n--- [2] BACKTEST & RISK METRICS ---")
    print(f"• Total Strategy Return: %{bt['total_return'] * 100:.2f} (Buy&Hold: %{bt['benchmark_return'] * 100:.2f})")
    print(f"• Annualized Return (CAGR) : %{bt['cagr'] * 100:.2f}")
    print(f"• Sharpe Ratio (365d)  : {bt['sharpe_ratio']:.2f}")
    print(f"• Annualized Volatility: %{bt['annualized_volatility'] * 100:.2f}")
    print(f"• Max Drawdown         : %{bt['max_drawdown'] * 100:.2f}")
    print(f"• Trade Win Rate       : %{bt['win_rate'] * 100:.2f} ({bt['num_trades']} Trades)")
    print(f"• Final Equity         : ${bt['final_value']:,.2f} (Start: ${bt['initial_capital']:,.2f})")
    print("=" * 80)
    print(f"✓ Markdown Report Saved : {md_report_path.resolve()}")
    print(f"✓ Figures Saved in      : {figures_dir.resolve()}\n")


if __name__ == "__main__":
    main()
